name: Push to Hugging Face

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  push_to_huggingface:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Hugging Face Hub
        run: pip install huggingface_hub

      - name: Set Hugging Face Token
        run: |
          mkdir -p ~/.huggingface
          echo "${{ secrets.HG }}" > ~/.huggingface/token
        shell: bash

      - name: Push files to Hugging Face
        run: |
          from huggingface_hub import Repository
          repo = Repository(local_dir="hack_hound", clone_from="rithuikprakash/hack_hound", use_auth_token=True)
          repo.push_to_hub()
        shell: python
